**Default value**

In [6]:
# X 0 0 0 0
# X X 0 0 0
# X X X 0 0 
# X X X 0 0
# X X X X 0
def draw_ascii_pattern(num_rows = 5):
    print(num_rows*"O")
    
draw_ascii_pattern()    
    
    

OOOOO


In [7]:
def draw_ascii_pattern(num_rows = 5):
    for i in range(num_rows):
        print(f'{i*"X"}{(num_rows-i)*"O"}')
        
    
draw_ascii_pattern(5)

OOOOO
XOOOO
XXOOO
XXXOO
XXXXO


\*args
**arbitrary number of positional arguments**

In [8]:
def mean_(*args):
    print(args)
mean_(1,2,3,4)    
#outprints tuple

(1, 2, 3, 4)


In [9]:
mean_(1,2)

(1, 2)


In [10]:
def mean_(*args):
    sum_ = 0
    
    for arg in args:
        sum_ += arg
    return sum_/len(args)
mean_(1,2,3)    

2.0

\*\*Kwargs


In [11]:
def print_kwargs(**options):
    print(options)
    print(f"{options.keys() = }")
    print(f"{options.values() = }")

print_kwargs(a = 5, is_active = True, age = 33)    


{'a': 5, 'is_active': True, 'age': 33}
options.keys() = dict_keys(['a', 'is_active', 'age'])
options.values() = dict_values([5, True, 33])


**File handling**

In [12]:
import re

with open("data/ml_text_raw.txt", 'r') as file:
    raw_text = file.read()

test_fixed_spacing = re.sub(r"\s+"," ",raw_text) 
test_fixed_spacing 

  

'SUperViseD LEARNinG IS a PaRt oF MaCHinE LEARniNG, wheRE aLgORithms LEARn FRom a tRAINIng DaTa Set. THese aLgORithms TRY TO MaKE SeNSe Of ThE DaTa BY MaTChiNG INpUtS TO CoRResPonDInG OutpUTs. In suPERviseD LEARNing, EACH DaTa PoINt in ThE tRAINIng Set IS LaBELEd WiTH ThE CoRReCT OutpUT, WHich aLLOWS thE ALgORithM To LEARn FRom ThE ExAMPles. THis alLOWS thE ALgORithM To MaKe PREDIcTions On UnSEEN DaTa, BaSED On ITs TRaiNIng. iT IS USEd FoR taSKS SuCH AS CLaSSIFICaTion, WheRE ThE GoAL IS To aSSIGn a LaBEL To InpUt DaTa, anD REGrESsIoN, WheRE ThE GoAL IS To PREDIcT a CoNtINuoUS OutpUT VaRIabLE. SuPERviseD LEARNing HaS MaNY APPLIcatIoNS In ArEas LIke Image ReCOGNitiON, NatuRaL LaNGuaGE PRoCESSINg, anD FiNaNCiaL FoRECasting.'

In [17]:
test_fixed_spacing.split(". ")

['SUperViseD LEARNinG IS a PaRt oF MaCHinE LEARniNG, wheRE aLgORithms LEARn FRom a tRAINIng DaTa Set',
 'THese aLgORithms TRY TO MaKE SeNSe Of ThE DaTa BY MaTChiNG INpUtS TO CoRResPonDInG OutpUTs',
 'In suPERviseD LEARNing, EACH DaTa PoINt in ThE tRAINIng Set IS LaBELEd WiTH ThE CoRReCT OutpUT, WHich aLLOWS thE ALgORithM To LEARn FRom ThE ExAMPles',
 'THis alLOWS thE ALgORithM To MaKe PREDIcTions On UnSEEN DaTa, BaSED On ITs TRaiNIng',
 'iT IS USEd FoR taSKS SuCH AS CLaSSIFICaTion, WheRE ThE GoAL IS To aSSIGn a LaBEL To InpUt DaTa, anD REGrESsIoN, WheRE ThE GoAL IS To PREDIcT a CoNtINuoUS OutpUT VaRIabLE',
 'SuPERviseD LEARNing HaS MaNY APPLIcatIoNS In ArEas LIke Image ReCOGNitiON, NatuRaL LaNGuaGE PRoCESSINg, anD FiNaNCiaL FoRECasting.']

In [14]:
sentences = [text.strip().capitalize() for text in test_fixed_spacing.split(".")]
sentences = sentences[:-1]
sentences


Supervised learning is a part of machine learning, where algorithms learn from a training data set.
These algorithms try to make sense of the data by matching inputs to corresponding outputs.
In supervised learning, each data point in the training set is labeled with the correct output, which allows the algorithm to learn from the examples.
This allows the algorithm to make predictions on unseen data, based on its training.
It is used for tasks such as classification, where the goal is to assign a label to input data, and regression, where the goal is to predict a continuous output variable.
Supervised learning has many applications in areas like image recognition, natural language processing, and financial forecasting


In [22]:

cleaned_text = ".\n".join(sentences)
print(cleaned_text)

Supervised learning is a part of machine learning, where algorithms learn from a training data set.
These algorithms try to make sense of the data by matching inputs to corresponding outputs.
In supervised learning, each data point in the training set is labeled with the correct output, which allows the algorithm to learn from the examples.
This allows the algorithm to make predictions on unseen data, based on its training.
It is used for tasks such as classification, where the goal is to assign a label to input data, and regression, where the goal is to predict a continuous output variable.
Supervised learning has many applications in areas like image recognition, natural language processing, and financial forecasting


In [23]:
with open("data/cleaned_ml_text.txt",'w') as file:
    file.write(cleaned_text)

## ERRORS
*Syntax errors* 
*runtime errors*
*logical errors*

In [25]:
#  prin("hello")

In [27]:
# Runtime error
numbers = list(range(5))
print(numbers)


[0, 1, 2, 3, 4]


In [6]:
import numpy as np

radius = 5

area_circle = np.pi*radius**2
print(f"{area_circle = :.2f}")

area_circle = 78.54


In [7]:
import math

radius = 5
area = math.pi * radius**2
print(f"{area = :.2f}")

area = 78.54


**TRY EXCEPT**

In [ ]:
age = float(input("Enter age : "))
age    

-5.0

In [11]:

age = float(input("Enter age : "))
if not 0 <= age <=125:
    raise ValueError("Age must ve between 0 and 12")   
print(f"You are {age} years old.")

You are 30.0 years old.


In [12]:
age = float(input("Enter age : "))
if not 0 <= age <=125:
    raise ValueError("Age must ve between 0 and 12")   
print(f"You are {age} years old.")

ValueError: Age must ve between 0 and 12

In [ ]:
try:
    age = float(input("Enter age : "))
    if not 0 <= age <=125:
        raise ValueError("Age must be between 0 and 12")   
    print(f"You are {age} years old.")
except ValueError as err:
    print(err)

Age must ve between 0 and 12


In [20]:
while True:
    try:
        age = float(input("Enter age : "))
        if not 0 <= age <= 125:
            raise ValueError("Age must be between 0 and 125")   
        print(f"You are {age} years old.")
        break
    except ValueError as err:
        print(err)

Age must be between 0 and 125
You are 12 years old.


In [1]:
# want user to try again 
while True: 
    try:
        age = float(input("Ange din ålder"))
        if not 0<=age<=125:
            raise ValueError("Åldern måste vara mellan 0 and 125")
        print(f"Du är {age} år gammal")
        break # breaks out of while loop if nothing went wrong
    except ValueError as err:
        print(err)   

Du är 25.0 år gammal


##Functions##

In [3]:
def squarer(x):
    return x**2

squarer(2),squarer(4),squarer(-3)

(4, 16, 9)

In [5]:
[squarer(x) for x in range(10)]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [12]:
def smallest(num1,num2):
    if num1 > num2:
        return num2
    return num1

smallest(2,1),smallest(7,7)    

(1, 7)

**Default value**

In [24]:
def draw(rows= 5):
    for i in range(1,rows + 1):
        print(i * "x " + (rows-i)*"O ")
draw()        

x O O O O 
x x O O O 
x x x O O 
x x x x O 
x x x x x 


In [34]:
def triangle(rad):
    for i in range(1,rad +1 ):
        print(i*"D " + (rad - i) * "IF ")
triangle(5)    

D IF IF IF IF 
D D IF IF IF 
D D D IF IF 
D D D D IF 
D D D D D 


In [35]:
def draw(rows= 3):
    for i in range(1,rows + 1):
        print(i * "x " + (rows-i)*"O ")
draw()  

x O O 
x x O 
x x x 


In [36]:
def draw(rows= 9):
    for i in range(1,rows + 1):
        print(i * "x " + (rows-i)*"O ")
draw()  

x O O O O O O O O 
x x O O O O O O O 
x x x O O O O O O 
x x x x O O O O O 
x x x x x O O O O 
x x x x x x O O O 
x x x x x x x O O 
x x x x x x x x O 
x x x x x x x x x 


In [37]:
draw(10)

x O O O O O O O O O 
x x O O O O O O O O 
x x x O O O O O O O 
x x x x O O O O O O 
x x x x x O O O O O 
x x x x x x O O O O 
x x x x x x x O O O 
x x x x x x x x O O 
x x x x x x x x x O 
x x x x x x x x x x 


**arbitrary \*arguments**

In [41]:
def my_mean(*args):
    print(args)
    sum_ = 0
    for arg in args:
        sum_ += arg
    return sum_/len(args)    
my_mean(1,2,3,4)

(1, 2, 3, 4)


2.5

**Keyword arguments** \*\*kwargs

In [47]:
import numpy as np

def simulate_dices(throws= 1,dices = 2):
    print(np.random.randint(1,7, (throws,dices)))
simulate_dices()    

[[3 2]]


In [48]:
simulate_dices(throws=4)

[[1 6]
 [3 4]
 [2 6]
 [6 3]]


In [49]:
simulate_dices(throws=5,dices=3)

[[3 6 3]
 [5 3 3]
 [5 4 3]
 [5 6 4]
 [2 5 1]]


In [50]:
simulate_dices(dices=3,throws=4)

[[6 1 5]
 [5 1 2]
 [4 6 6]
 [4 2 2]]


In [51]:
simulate_dices(dices=4)

[[2 4 1 5]]


In [ ]:
simulate_dices